BINEXT   = 
RUN      = ./
RM       = rm -rfv
OFLAG    = -o
OBJEXT   = o
OBJFLAGS = -c -o
DIR_SEP  = /
COV      = lcov_tests.info
MISSED   = missed.txt
CLEAN    = *.nml *.mod src$(DIR_SEP)*.$(OBJEXT) $(MISSED) src$(DIR_SEP)rev.f90 rev.tex *.gcda *.gcno *.lst test_* *.dbg src$(DIR_SEP)*.gcda src$(DIR_SEP)*.gcno src$(DIR_SEP)*.lst src$(DIR_SEP)*.optrpt *.optrpt *.log *.opt.yaml $(COV) html-cov$(DIR_SEP) *.csv
CMP      = cmp
PYTHON   = python3
ARCH     = 
GREP     = grep -n
CP       = cp

LOOP_START  = for i in 
LOOP_MIDDLE = ; do 
LOOP_END    = $$i ; done
