#######################
# Manual dependencies #
#######################

src$(DIR_SEP)rev.f90 rev.tex: $(ALLSRC)
	$(PYTHON) py$(DIR_SEP)gitrev.py

# jom needs explicit dependencies listed for all files.
src$(DIR_SEP)rev.$(OBJEXT): src$(DIR_SEP)rev.f90

depends: src$(DIR_SEP)units.f90

# Needs to be manually present as this is autogenerated and not available for depends.py to find.
src$(DIR_SEP)units.f90: src$(DIR_SEP)genunits.nml
	genunits$(BINEXT) src$(DIR_SEP)genunits.nml

src$(DIR_SEP)geninput_springer_subroutine.f90 src$(DIR_SEP)geninput_springer.tex: src$(DIR_SEP)geninput_springer.nml
	geninput$(BINEXT) src$(DIR_SEP)geninput_springer.nml

test_conservation.csv: test_cva$(BINEXT)
	$(RUN)test_cva$(BINEXT)

test_exact.tex: test_cva$(BINEXT)
	$(RUN)test_cva$(BINEXT)

###########################
# Files to manually clean #
###########################

CLEAN_MANUAL = test_conservation.nml
