#######################
# Manual dependencies #
#######################

src$(DIR_SEP)rev.f90: $(ALLSRC)
	$(PYTHON) py$(DIR_SEP)gitrev.py

# jom needs explicit dependencies listed for all files.
src$(DIR_SEP)rev.$(OBJEXT): src$(DIR_SEP)rev.f90

depends: src$(DIR_SEP)units.f90

# Needs to be manually present as this is autogenerated and not available for depends.py to find.
src$(DIR_SEP)units.f90: src$(DIR_SEP)genunits.nml
	genunits$(BINEXT) src$(DIR_SEP)genunits.nml

src$(DIR_SEP)geninput_springer_subroutine.f90: src$(DIR_SEP)geninput_springer.nml
	geninput$(BINEXT) src$(DIR_SEP)geninput_springer.nml

###########################
# Files to manually clean #
###########################

CLEAN_MANUAL = 
